#!/usr/bin/env python3
"""Gera laco/estado.json do lacço PLATAFORMA ENTERPRISE (só na criação; depois o estado é editado pelo turno)."""
import json, pathlib, datetime
B = pathlib.Path("/home/dev/plataforma/laco")
hoje = datetime.date.today().isoformat()

def item(id, linha, pri, hip, portao, refut, dep=(), papeis=()):
    return {"id": id, "linha": linha, "prioridade": pri, "estado": "pendente", "dependencias": list(dep),
            "hipotese": hip, "portao_de_pronto": portao, "refutacao": refut, "papeis": list(papeis),
            "tentativas": 0, "turno": None, "bloqueio": None}

BL = []
# ---------------- L0 FUNDAÇÃO ----------------
BL += [
item("L0-01-repo", "L0 fundação", 1,
 "um repositório único (plataforma/enterprise) com layout fixo, instalador idempotente, esquema `plat` próprio no iagro_sat, role própria, pg_hba, unidade systemd `plat-api` e nginx interno noindex = tudo o que vem depois tem onde morar",
 "git com README/ARQUITETURA/MANUAL/CHANGELOG; `install.sh` cria schema+role+pg_hba (com linha em pg_hba.conf) e sobe `plat-api` (:8150) sem erro em máquina que nunca viu o repo; `make check` roda pytest verde; URL interna HTTPS com noindex responde 200 em /saude com JSON de versão; `docs/adr/0001-fundacao.md` escrito",
 "adversário apaga schema `plat` e role, roda install.sh de novo, confere que sobe e que /saude e um pytest completo passam; confere noindex no cabeçalho",
 papeis=("arquiteto","dados","backend","testador","adversario")),
item("L0-02-tenant-auth", "L0 fundação", 1,
 "inquilino + usuário + perfil + sessão + 2FA + token de serviço (revogável, com log de leitura) — herdado do SIG de teste interno e generalizado; RLS em TODA tabela com tenant_id",
 "tabelas tenant/usuario/sessao/token/permissao com RLS ativa; login/logout/2FA/troca de senha/usuários (admin) funcionam pelo navegador (e2e playwright com captura); teste automatizado prova que usuário do inquilino A não lê nem edita linha do B em nenhum endpoint (varredura de todas as rotas); token de serviço aparece no log com IP/rota/bytes",
 "adversário escreve consultas cruzadas e chamadas com token de outro inquilino em todas as rotas listadas no OpenAPI; qualquer 200 cruzado = refutado",
 dep=("L0-01-repo",), papeis=("dados","backend","frontend","testador","adversario")),
item("L0-03-catalogo", "L0 fundação", 1,
 "catálogo de conteúdo por inquilino (item = camada vetorial, raster, mapa, app, painel, formulário, fluxo, rede) com metadado, tags, dono, compartilhamento (privado/grupo/inquilino/link por token), busca e miniatura — o equivalente ao Portal 'Content'",
 "tabela item + grupo + compartilhamento; tela 'Conteúdo' com lista/grade, busca, filtros por tipo/tag/dono, criar pasta, compartilhar, excluir, e detalhe do item com metadado editável; e2e cobre criar-editar-compartilhar-excluir; OpenAPI publicado; paridade escrita contra Portal Content (feito/parcial/fora)",
 "adversário compara a lista de ações do Portal 'Content' (doc Esri datada) com a tela e marca o que falta; item compartilhado por link tem de negar acesso após revogação",
 dep=("L0-02-tenant-auth",), papeis=("esri","arquiteto","backend","frontend","testador","adversario")),
item("L0-04-ingest-vetor", "L0 fundação", 1,
 "upload de shapefile(zip)/GeoPackage/GeoJSON/KML/CSV(lat,lon)/DXF-DWG(via ODA/ezdxf) vira camada PostGIS do inquilino com CRS detectado, campos tipados, índice espacial, validação (ST_MakeValid), estatísticas e página de camada",
 "cada formato listado importa por upload no navegador e aparece no mapa em ≤ 60 s para 100 mil feições; CRS errado/ausente é perguntado, não assumido; feições inválidas contadas e corrigidas com relatório; teste automatizado com arquivo de cada formato (dado aberto); tamanho máximo e cota por inquilino aplicados",
 "adversário envia shapefile sem .prj, GeoJSON com polígono auto-intersectado, CSV com vírgula decimal e DXF com blocos; cada um tem de ou importar certo ou recusar com mensagem exata — silêncio = refutado",
 dep=("L0-03-catalogo",), papeis=("dados","backend","frontend","testador","adversario")),
item("L0-05-jobs", "L0 fundação", 2,
 "fila de trabalho só com Postgres (Procrastinate ou própria) para ingestão, geoprocessamento, COG, IA: progresso, cancelamento, log por job, retentativa, visível na tela 'Tarefas'",
 "job de 5 min mostra progresso em tempo real, pode ser cancelado, sobrevive a reinício do serviço (retoma ou marca falha, nunca some); 1 worker por padrão com limite de RAM declarado; tela Tarefas por inquilino; teste automatizado",
 "adversário mata o worker no meio de um job e reinicia: job não pode aparecer como concluído",
 dep=("L0-01-repo",), papeis=("backend","testador","adversario")),
item("L0-06-backup-status", "L0 fundação", 3,
 "pgBackRest (ou pg_basebackup+WAL) com PITR, dump por inquilino em formato aberto (GeoPackage+JSON) sob demanda, restore drill scriptado, página de status e log de correções",
 "backup diário + WAL; `restore_drill.sh` restaura em schema temporário e confere contagens = produção; botão 'exportar meu inquilino' gera GeoPackage completo; página /status pública interna com uptime dos serviços; teste do drill no CI",
 "adversário restaura o backup mais recente em schema à parte e compara COUNT(*) de todas as tabelas com tenant_id; divergência = refutado",
 dep=("L0-04-ingest-vetor",), papeis=("dados","backend","testador","adversario")),
]
# ---------------- L1 IMAGENS ----------------
BL += [
item("L1-01-ingest-raster", "L1 imagens", 1,
 "upload de GeoTIFF/JP2/ECW(se GDAL)/ortomosaico vira COG (visual JPEG/WEBP + científico ZSTD) no Garage com item STAC (pgstac) e entra no catálogo do inquilino com miniatura e estatísticas",
 "upload pelo navegador → job → COG validado (rio-cogeo) → item STAC em pgstac → aparece em Conteúdo e no mapa; tempo e taxa de compressão registrados por job; pgstac instalado e migrado; teste com S2 e ortofoto abertos",
 "adversário envia raster sem CRS, com nodata errado e 16 bits: cada um importa certo ou recusa com mensagem; conferir que o COG lê por Range (206) e que sobrescrever não corrompe (nome por sha)",
 dep=("L0-05-jobs","L0-03-catalogo"), papeis=("raster","backend","testador","adversario")),
item("L1-02-tiles-token", "L1 imagens", 1,
 "serviço de tiles raster por inquilino: XYZ/WMTS 1.0.0/TileJSON com token longo no caminho, revogável, restrito por Referer/IP, com log de leitura; NDVI e expressões ao vivo; mosaico por coleção",
 "URLs `/svc/<token>/raster/<item>/{z}/{x}/{y}` e WMTS GetCapabilities válidas; QGIS carrega WMTS e XYZ; token revogado → 403 em ≤ 5 s; expressão NDVI via parâmetro; log com contagem por token; bench: ≥ 500 tiles/s quente com cache nginx",
 "adversário tenta URL arbitrária no parâmetro (SSRF), token de outro inquilino, Referer falso; e valida o XML do WMTS com o esquema OGC",
 dep=("L1-01-ingest-raster","L0-02-tenant-auth"), papeis=("raster","esri","backend","testador","adversario")),
item("L1-03-conectores-sensores", "L1 imagens", 2,
 "conectores prontos, sem chave do cliente: Sentinel-2 (Element84 STAC), Sentinel-1 (onde houver COG aberto), Landsat (USGS STAC), MapBiomas col.10 (COG), ESA WorldCover, JRC água, Hansen, GLO-30, NASA POWER, SoilGrids, Copernicus CDS (AgERA5/ERA5) com a chave da casa — o usuário desenha/seleciona área e período e a camada entra no catálogo dele",
 "tela 'Sensores' lista conectores com estado (testado por HTTP na hora); para cada um, área+período → job → camada no catálogo; série NDVI por polígono em ≤ 90 s; cada conector com teste automatizado que baixa 1 recorte pequeno; licença de cada fonte escrita na ficha",
 "adversário confere licença e URL de cada conector contra a página oficial datada e roda cada um numa área nova; conector que falha silenciosamente = refutado",
 dep=("L1-01-ingest-raster",), papeis=("raster","pesquisador","backend","testador","adversario")),
item("L1-04-serie-temporal", "L1 imagens", 3,
 "série temporal por camada raster (data no STAC): controle deslizante de tempo no mapa, comparação lado a lado/cortina, gráfico de índice por polígono, exportação CSV",
 "mapa com controle de tempo sobre coleção com ≥ 6 datas; cortina e lado a lado funcionam (e2e); gráfico NDVI/qualquer índice por feição desenhada; CSV baixa; paridade contra 'Time slider'/Image Analyst escrita",
 "adversário confere que a data mostrada é a do STAC e não a do upload; compara valor do gráfico com cálculo independente em rasterio",
 dep=("L1-02-tiles-token","L1-03-conectores-sensores"), papeis=("raster","frontend","testador","adversario")),
item("L1-05-ia-na-entrada", "L1 imagens", 4,
 "inferência opcional na ingestão (GPU box): detecção de mudança S2, telhado/edificação (Open Buildings como base), vegetação em faixa — gera camada leve com proveniência (modelo, versão, data, hash)",
 "pelo menos 1 modelo em produção na entrada com opção por inquilino; camada resultante tem metadado de proveniência; teste com área conhecida; NUNCA afirma o que não foi medido (frase de enquadramento na camada)",
 "adversário roda o modelo em área de controle e confere taxa de falso positivo declarada na ficha",
 dep=("L1-03-conectores-sensores","L0-05-jobs"), papeis=("raster","pesquisador","backend","adversario")),
]
# ---------------- L2 PLATAFORMA (dado do cliente → plataforma) ----------------
BL += [
item("L2-01-mapa-web", "L2 plataforma", 1,
 "visualizador MapLibre próprio: camadas do catálogo (vetor via Martin/PMTiles, raster via tiles), ordem, opacidade, legenda, popup, escala, coordenadas, medição, pesquisa de endereço/coordenada, base cartográfica (OSM + satélite aberta), impressão",
 "Martin instalado (`plat-martin` :8151) servindo funções com RLS; mapa carrega camada de 1 mi de feições sem travar (medido); todos os controles listados funcionam por e2e; legenda gerada da simbologia; impressão gera PNG/PDF com escala e norte; 0 erro de console",
 "adversário carrega 10 camadas ao mesmo tempo e mede tempo e memória do navegador; testa popup em feição com campo nulo e geometria multi",
 dep=("L0-04-ingest-vetor",), papeis=("cartografo","frontend","backend","testador","adversario")),
item("L2-02-simbologia", "L2 plataforma", 1,
 "editor de simbologia completo: único, por categoria, por classe (quantil/intervalo/natural), proporcional, mapa de calor, rótulos com expressão, transparência, escala de visibilidade, para ponto/linha/polígono e raster (rampa, faixa, transparência)",
 "cada tipo de simbologia acima aplicável pelo navegador e salvo no mapa; rótulos com prioridade de colisão; rampas ColorBrewer; estilo exportável como JSON (spec MapLibre) e importável; e2e por tipo; paridade contra Smart Mapping do Map Viewer escrita",
 "adversário aplica classificação em campo com nulos e valores repetidos; compara cortes com cálculo independente (numpy)",
 dep=("L2-01-mapa-web",), papeis=("cartografo","frontend","testador","adversario")),
item("L2-03-edicao", "L2 plataforma", 1,
 "edição de feições no mapa: criar/mover/vértices/dividir/unir/apagar, formulário de atributos com domínios e validação, anexos, desfazer/refazer, snapping, edição em lote, histórico de versão por feição (quem/quando/o quê) e restauração",
 "todas as operações por e2e; domínios e obrigatórios aplicados no servidor (não só no navegador); histórico consultável e restauração funciona; edição concorrente detectada (versão otimista); anexos com limite e tipos",
 "adversário edita a mesma feição em duas sessões e confere que a última não sobrescreve em silêncio; envia atributo fora do domínio direto na API",
 dep=("L2-01-mapa-web","L0-02-tenant-auth"), papeis=("backend","frontend","testador","adversario")),
item("L2-04-servicos-esri-ogc", "L2 plataforma", 1,
 "toda camada do inquilino publicada automaticamente como FeatureServer Esri-compatível (query com where/geometry/outFields/orderBy/paginação/estatísticas, applyEdits, attachments, relacionamentos, queryRelatedRecords) E OGC API Features/WFS 2.0 E tiles vetoriais, tudo por token",
 "conformidade medida: script de conformidade que percorre a spec REST do FeatureServer (parâmetros da doc Esri datada) e marca cada um; ArcGIS Pro/QGIS/AGOL carregam (QGIS medido aqui; Pro/AGOL = teste do parceiro registrado como PENDENTE, nunca como feito); OGC API Features passa no `ogcapi-features` validator (teamengine ou pyogcapi) para o núcleo; WFS 2.0 GetCapabilities válido",
 "adversário roda o cliente Python `arcgis` (Esri) e `owslib` contra o serviço e lista toda chamada que quebra",
 dep=("L2-03-edicao","L0-02-tenant-auth"), papeis=("esri","backend","testador","adversario")),
item("L2-05-geoprocessamento", "L2 plataforma", 2,
 "ferramentas de análise no navegador (executam no servidor como job): buffer, recorte, interseção, união, dissolver, junção espacial, centroides, área/comprimento, agregação por polígono, seleção por atributo/local, isócrona (OSRM), rota, estatísticas zonais sobre raster, calculadora raster, reprojeção, criação de grade hex/quadrada",
 "cada ferramenta com formulário, execução como job, resultado como nova camada no catálogo com proveniência (entrada+parâmetros+versão); teste automatizado por ferramenta contra resultado calculado independentemente (shapely/rasterio); paridade contra Analysis tools do Map Viewer escrita",
 "adversário compara cada saída com QGIS processing (qgis_process headless) na mesma entrada; divergência > tolerância declarada = refutado",
 dep=("L2-01-mapa-web","L0-05-jobs"), papeis=("dados","backend","frontend","testador","adversario")),
item("L2-06-paineis", "L2 plataforma", 2,
 "painéis (dashboards) ligados a camadas: indicador, gráfico de barras/linha/pizza, tabela, lista, mapa, filtro por seleção; atualização quando o dado muda; compartilhável por link",
 "editor de painel arrasta-e-solta (grade), cada elemento configurável; filtro em um elemento filtra os outros (ação); e2e; dado muda no banco → painel reflete sem recarregar (polling/SSE) ; paridade contra ArcGIS Dashboards escrita",
 "adversário confere que soma/média do indicador bate com SQL direto e que painel de inquilino A não vaza para B pelo link",
 dep=("L2-01-mapa-web",), papeis=("frontend","backend","testador","adversario")),
item("L2-07-campo", "L2 plataforma", 3,
 "formulários de campo (construtor XLSForm-compatível) com coleta em celular via PWA offline (fila local + sincronização), foto/GPS/assinatura; integração ODK Central opcional",
 "construtor de formulário arrasta-e-solta gera XLSForm válido; PWA instala no celular, coleta offline 10 registros e sincroniza; registros viram feições na camada; e2e em viewport móvel; paridade contra Survey123/Field Maps escrita",
 "adversário coleta sem rede, muda relógio, sincroniza duas vezes: sem duplicata e sem perda",
 dep=("L2-03-edicao",), papeis=("frontend","backend","testador","adversario")),
item("L2-08-migracao-agol", "L2 plataforma", 2,
 "ferramenta de migração: dado um Portal/AGOL do cliente (token dele), clona itens (camadas hospedadas, web maps, grupos, simbologia simples, Survey123→XLSForm), gera relatório do que entrou e do que NÃO entra (Arcade, Experience Builder, StoryMaps, Dashboards com ações)",
 "roda contra conta AGOL de teste (a parceiro geo tem — item PENDENTE de credencial do parceiro; até lá, contra JSON exportado de web map público) e produz catálogo espelho + relatório; web map clonado abre no nosso visualizador com mesmas camadas e simbologia simples; teste automatizado com JSON de exemplo",
 "adversário compara camada por camada, contagem e simbologia; item marcado 'migrado' com diferença = refutado",
 dep=("L2-02-simbologia","L0-04-ingest-vetor"), papeis=("esri","backend","testador","adversario")),
item("L2-09-3d", "L2 plataforma", 3,
 "cena 3D: terreno (GLO-30 terrain-RGB), extrusão por atributo, modelos (glTF/IFC convertidos), iluminação, corte, medição em 3D",
 "cena com terreno + extrusão + 1 modelo IFC convertido abre e roda a 30 fps em máquina comum (medido); e2e; paridade contra Scene Viewer escrita",
 "adversário confere altura extrudada contra atributo e que o terreno não tem degrau de 128 m (armadilha terrain-RGB)",
 dep=("L2-01-mapa-web",), papeis=("frontend","cartografo","testador","adversario")),
]
# ---------------- L3 MOTOR AMC ----------------
BL += [
item("L3-01-motor-servico", "L3 motor AMC", 1,
 "motor multicritério como serviço da plataforma: fator = camada + critério (transformação declarada: linear, faixas, distância, categoria→nota, veto), peso escolhido pelo usuário, unidade de análise = grade hex/quadrada ou feições do usuário, favorabilidade 0-100 explicável por célula/feição; herdado dos motores logístico (25 fatores) e de LT (322 camadas)",
 "tela 'Motor' em qualquer camada de unidades: adicionar fatores de camadas do catálogo, definir transformação com pré-visualização de histograma, pesos, vetos, 'rodar' como job, resultado como camada com explicação por unidade (fator × peso, Σ, vetado); presets salvos; export do método em PDF/JSON; teste contra o motor logístico (mesmos fatores = mesma nota ±0,5)",
 "adversário recalcula 200 unidades em numpy a partir dos rasters/vetores de entrada e compara; divergência > 0,5 ponto = refutado; e tenta peso negativo/soma zero",
 dep=("L2-05-geoprocessamento",), papeis=("arquiteto","dados","backend","frontend","testador","adversario")),
item("L3-02-robustez", "L3 motor AMC", 3,
 "análise de robustez do motor: sensibilidade por fator (Sobol/SMAA simplificado), ranking estável × instável, comparação de presets lado a lado, Monte Carlo de pesos",
 "botão 'robustez' gera relatório com ranking sob N sorteios de pesos e marca unidades estáveis; comparação de 2 presets no mapa; teste automatizado; texto 'pesos escolhidos, não medidos' em todo resultado",
 "adversário confere que ranking estável não muda com permutação de pesos dentro da faixa declarada",
 dep=("L3-01-motor-servico",), papeis=("dados","backend","frontend","adversario")),
]
# ---------------- L4 REDE DE UTILIDADES ----------------
BL += [
item("L4-01-modelo-rede", "L4 rede de utilidades", 1,
 "modelo de rede de utilidades genérico (elétrica/água/gás/telecom): nós (junção, dispositivo, fonte/sub, consumidor) e arestas (trecho/condutor) com conectividade explícita (tabela de associação), estado (aberto/fechado), hierarquia (subestação→alimentador→trafo→BT), atributos por tipo, regras de conectividade por catálogo de ativos; PostGIS + pgRouting",
 "pgRouting instalado; DDL `plat.rede_*` com regras de conectividade validadas por trigger; importador BDGD (ANEEL) que monta a rede de 1 distribuidora inteira (SUB/CTMT/SSDMT/UNTRMT/SSDBT/UCBT) com contagem conferida contra o arquivo; documento do modelo com paridade contra ArcGIS Utility Network (domínios, tiers, associations, subnetworks) escrita",
 "adversário importa a BDGD de outra distribuidora e confere: nº de alimentadores, km por nível, trafos e UCs = o que o arquivo declara; nó órfão e aresta sem nó contados e explicados",
 dep=("L0-04-ingest-vetor",), papeis=("redes","pesquisador","arquiteto","dados","backend","adversario")),
item("L4-02-tracado", "L4 rede de utilidades", 1,
 "traçados de rede: conectado, montante, jusante, isolamento (dispositivos a abrir), laço, caminho mais curto, subrede (alimentador) e barreiras — como serviço e no mapa com seleção",
 "cada traçado por API e no visualizador (clicar um ponto → resultado destacado com contagem e lista de ativos); tempo ≤ 2 s em alimentador de 10 mil trechos (medido); teste automatizado contra rede sintética com resposta conhecida; paridade contra os trace types do UN escrita",
 "adversário monta rede com laço e chave aberta e confere que jusante respeita o estado; recalcula isolamento à mão",
 dep=("L4-01-modelo-rede",), papeis=("redes","backend","frontend","testador","adversario")),
item("L4-03-edicao-rede", "L4 rede de utilidades", 2,
 "edição de rede com regras: inserir dispositivo em trecho (divide e reconecta), mover nó arrasta as arestas, apagar trecho avisa desconexão, validar topologia (área suja), versões de edição (rascunho→revisão→publicado)",
 "operações no mapa por arrasta-e-solta com snapping; validação de topologia devolve erros com posição; versões com diff e publicação; e2e; regras de conectividade recusam ligação proibida no servidor",
 "adversário liga MT em BT direto pela API e conecta trecho a nó inexistente: tem de ser recusado com mensagem",
 dep=("L4-02-tracado","L2-03-edicao"), papeis=("redes","backend","frontend","testador","adversario")),
item("L4-04-subredes-diagramas", "L4 rede de utilidades", 3,
 "subredes calculadas e mantidas (nome do alimentador propagado, controlador), sumários por subrede (km, clientes, carga), diagrama esquemático automático (layout ortogonal) do alimentador",
 "atualização de subrede após edição; tabela de sumário por alimentador conferida contra BDGD; diagrama esquemático abre e se navega ligado ao mapa; e2e",
 "adversário abre chave de fronteira e confere que a subrede re-atribui os trechos",
 dep=("L4-03-edicao-rede",), papeis=("redes","backend","frontend","adversario")),
item("L4-05-conectores-rede", "L4 rede de utilidades", 3,
 "conectores: BDGD (ANEEL, 101 distribuidoras, já na casa), SINDAT/ONS (transmissão), CNEFE/consumidores, OSM power=*, e exportação CIM (IEC 61970/61968 XML) e OpenDSS",
 "importar BDGD de qualquer distribuidora pelo nome (pacote ANEEL) como job; exportar alimentador em OpenDSS e o `dss` roda power flow sem erro; CIM XML valida contra esquema; teste automatizado",
 "adversário roda OpenDSS e confere que nº de barras e linhas = nossos trechos e nós",
 dep=("L4-01-modelo-rede",), papeis=("redes","backend","testador","adversario")),
]
# ---------------- L5 BUILDER arrasta-e-solta ----------------
BL += [
item("L5-01-app-builder", "L5 builder", 2,
 "construtor de aplicação arrasta-e-solta: layout (cabeçalho, barra lateral, abas), widgets (mapa, legenda, lista de camadas, busca, filtro, tabela, gráfico, texto, imagem, botão de ação, formulário), temas, publicação por link/token, versão publicada × rascunho",
 "criar app do zero só arrastando, com ≥ 8 widgets funcionando entre si (seleção no mapa filtra tabela e gráfico), publicar, abrir por link anônimo com token; e2e; paridade contra Experience Builder (widgets e ações) escrita",
 "adversário abre o app publicado em viewport móvel e desktop e lista widget que quebra; muda rascunho e confere que a versão publicada não muda até publicar",
 dep=("L2-06-paineis","L2-02-simbologia"), papeis=("frontend","backend","esri","testador","adversario")),
item("L5-02-fluxos", "L5 builder", 2,
 "construtor de fluxos de geoprocessamento (nós e ligações, estilo Carto Workflows/ModelBuilder): entrada camada → ferramentas de L2-05 e motor L3 → saída camada; salvar, agendar, executar como job, ver proveniência",
 "fluxo com ≥ 5 nós roda e gera camada; agendamento (cron) re-executa; erro em nó mostra onde parou; fluxo exportável como JSON e como script Python equivalente; e2e",
 "adversário monta fluxo com ciclo e com tipo incompatível (raster em buffer vetorial): tem de recusar antes de rodar",
 dep=("L2-05-geoprocessamento","L3-01-motor-servico","L0-05-jobs"), papeis=("frontend","backend","testador","adversario")),
item("L5-03-form-builder", "L5 builder", 3,
 "construtor de formulário de atributos arrasta-e-solta para camadas (grupos, condicional, cálculo, domínio, obrigatório) usado na edição e no campo",
 "formulário definido por arrasto vale na edição web e no PWA de campo; regra condicional e cálculo funcionam nos dois; e2e",
 "adversário define campo obrigatório e submete sem ele pela API",
 dep=("L2-03-edicao","L2-07-campo"), papeis=("frontend","backend","testador","adversario")),
item("L5-04-storymap", "L5 builder", 4,
 "narrativas com mapa (StoryMap): seções de texto + mapa que voa para vista/camadas por seção, imagens, publicação por link",
 "criar narrativa de 5 seções, publicar, abrir por link; e2e",
 "adversário confere que vista por seção é a salva (sem deriva) e link revogado nega",
 dep=("L2-01-mapa-web",), papeis=("frontend","testador","adversario")),
]
# ---------------- L6 CONECTORES DE DADO BRASILEIRO ----------------
BL += [
item("L6-01-acervo-casa", "L6 conectores", 2,
 "o acervo da casa (376 fontes, 132 populadas no principal) como catálogo assinável de camadas prontas: o inquilino 'adiciona' camada do acervo (CAR, SIGEF, UC/TI, embargos, BDGD, hidrografia, relevo, MapBiomas, CNEFE…) com licença, frescor, sha256 e procedência lidos de `acervo.*`",
 "tela 'Acervo' com busca por domínio e fonte, ficha com licença/frescor/procedência, botão 'adicionar ao meu mapa' que vira camada só-leitura (view RLS) sem copiar dado; ≥ 40 camadas expostas com licença ESCRITA (nunca as sem licença — regra D17); teste automatizado",
 "adversário confere que nenhuma camada sem licença escrita aparece e que a ficha bate com `acervo.fonte`",
 dep=("L2-01-mapa-web",), papeis=("dados","backend","frontend","adversario")),
item("L6-02-conectores-vivos", "L6 conectores", 3,
 "conectores a serviços vivos por URL: WMS/WMTS/WFS/OGC API/ArcGIS REST externos (ler camadas de qualquer Portal público), STAC externo, GeoParquet no bucket (DuckDB), PMTiles",
 "adicionar camada por URL de cada tipo pelo navegador e vê-la no mapa; catálogo guarda a conexão com teste de saúde; teste automatizado contra endpoints públicos (IBGE, ANA, ANM)",
 "adversário fornece URL interna (SSRF) e serviço com CRS exótico",
 dep=("L2-01-mapa-web",), papeis=("backend","frontend","testador","adversario")),
]
# ---------------- L7 OPERAÇÃO / PRODUÇÃO ----------------
BL += [
item("L7-01-instalador-limpo", "L7 operação", 2,
 "instalação do zero em máquina limpa (docker compose OU install.sh em Ubuntu 24.04): Postgres+PostGIS+pgRouting+pgstac, Garage, Martin, TiTiler, API, front, nginx — 1 comando, ≤ 30 min, com dado de demonstração aberto",
 "instalação executada em ambiente limpo (contêiner nesta máquina ou GPU box) a partir do repositório e passa `make check` inteiro + e2e; documento de instalação; tamanho do repositório ≤ 3 GB",
 "adversário instala seguindo só o documento, sem falar com ninguém, e anota cada passo que falhou",
 dep=("L2-04-servicos-esri-ogc","L1-02-tiles-token"), papeis=("arquiteto","backend","testador","adversario")),
item("L7-02-carga", "L7 operação", 3,
 "teste de carga k6: 100 usuários simultâneos navegando mapa (tiles vetor+raster) e 20 editando; medir p95 e erro; ajustar cache e pool",
 "k6 instalado; cenário reproduzível em `tests/carga/`; p95 tile < 200 ms quente e 0 erro 5xx com 100 usuários; relatório com números e comando",
 "adversário repete o k6 com cache frio e publica os dois números",
 dep=("L7-01-instalador-limpo",), papeis=("backend","testador","adversario")),
item("L7-03-seguranca", "L7 operação", 2,
 "lista de segurança executada: cabeçalhos, CSP, rate limit, senha/2FA, tokens com escopo, RLS em tudo, upload seguro (tipo/tamanho/antivírus opcional), SSRF, injeção em where do FeatureServer, dependências com CVE",
 "checklist em `docs/SEGURANCA.md` com cada item marcado por teste automatizado ou evidência; scanner de dependências no `make check`; teste de injeção no `where` do FeatureServer passa",
 "adversário com instrução de invadir: tenta SQLi no where, path traversal em anexos, token de outro inquilino, upload de .svg com script; qualquer sucesso = refutado",
 dep=("L2-04-servicos-esri-ogc",), papeis=("backend","testador","adversario")),
item("L7-04-manual-e-tour", "L7 operação", 3,
 "manual do usuário completo (por tela, com captura real do produto) + manual do administrador + tour guiado dentro do produto para o primeiro acesso",
 "MANUAL.md/site interno com uma seção por tela e captura gerada por playwright (nunca desenho); tour no primeiro login; e2e do tour",
 "adversário segue o manual para fazer 5 tarefas sem ajuda e anota onde travou",
 dep=("L5-01-app-builder",), papeis=("cronista","frontend","adversario")),
item("L7-05-producao-final", "L7 operação", 4,
 "estado de produção: todos os itens L0-L6 entregues, instalação limpa aprovada, carga aprovada, segurança aprovada, backup/restore drill aprovado, manual completo, roteiro de demonstração para o dono, e página interna única atualizada",
 "todas as dependências `entregue`; roteiro `docs/DEMO.md` de 30 min percorrível por e2e; página interna do laço (noindex) com placar, capturas e o que NÃO faz (fronteira); nenhum placeholder no produto (varredura do driver = 0)",
 "adversário final com instrução de achar qualquer função que não funcione como o manual diz",
 dep=("L7-01-instalador-limpo","L7-02-carga","L7-03-seguranca","L7-04-manual-e-tour","L0-06-backup-status","L1-04-serie-temporal","L3-02-robustez","L4-04-subredes-diagramas","L4-05-conectores-rede","L5-02-fluxos","L5-03-form-builder","L6-01-acervo-casa","L6-02-conectores-vivos","L2-08-migracao-agol","L2-09-3d","L1-05-ia-na-entrada","L5-04-storymap"),
 papeis=("gerente","adversario")),
]

estado = {
 "objetivo": "Construir, testar, refutar e ENTREGAR em produção uma plataforma SIG corporativa própria, 100 % pilha aberta, que substitui o ArcGIS Enterprise para o cliente: L1 imagens (COG/STAC/tiles por inquilino + conectores Sentinel/NASA/Copernicus/MapBiomas), L2 plataforma (dado do cliente vira catálogo, mapas, edição, serviços Esri-compatíveis e OGC, análise, painéis, campo, migração), L3 motor multicritério explicável, L4 rede de utilidades (modelo, traçado, edição com regras, BDGD), L5 construtores arrasta-e-solta (app, fluxo, formulário, narrativa), L6 conectores ao acervo da casa, L7 operação de produção. Sem limite de turnos nem de tempo. Sem placeholder: função que aparece na tela funciona. Cada item só fecha quando o PORTÃO DE PRONTO passa cláusula a cláusula e um adversário independente não refuta.",
 "produto": {"codinome": "plat", "nome_publico": "PENDENTE (D18 do dono)", "repo": "/home/dev/plataforma/enterprise",
             "schema": "plat", "role": "plat_app", "portas": "8150-8159 (api 8150, martin 8151, titiler 8152, worker 8153)",
             "unidades_systemd": "plat-*", "url_interna": "PENDENTE (item L0-01 decide subdomínio × caminho; noindex, nunca linkar)"},
 "estado": "ATIVO", "turno": 0, "orcamento_turnos": None, "autoturno": True, "criado": hoje,
 "regras_herdadas": "CLAUDE.md da casa inteiro (análise/beta privado; sem PII; sem nome de cliente em material da plataforma; sem preço Esri; dado aberto) + METODOLOGIA.md do tracado-lt (número nunca digitado, régua declarada, portão congelado, quem produz não aprova, erro nunca é sucesso, ausência de dado nunca vira medição) + regras de escrita para cliente (03/09).",
 "guardrails": [
   "DISCO: conferir `df` antes de qualquer download; nenhum dado novo > 2 GB sem decisão do dono; repositório ≤ 3 GB; dado de demonstração só aberto e pequeno; cache em scratchpad, nunca em /tmp",
   "RAM: `free -g` available ≥ 4 GB antes de lançar agente ou job pesado; ≤ 3 agentes em paralelo; 1 job de máquina por vez (setsid nohup + log); 20 sessões claude derrubaram o Postgres em 30/08",
   "NUNCA tocar fgr/sig, cbre/sig, sigcorp, cbresig, geoapp, plataforma/pipeline em produção — copiar código, não editar; `bash /home/dev/fgr/sig/pipeline/testar.sh` = 9/9 depois de qualquer mexida em banco compartilhado",
   "schema `plat` + role `plat_app` + linha no pg_hba.conf (role nova sem pg_hba sobe e quebra na 1ª consulta); nginx: editar sites-enabled/iagrosat-db (não é symlink); portas 8150-8159",
   "publicação externa, contato com cliente/parceiro, DNS público e preço são atos do dono; o laço publica só em URL interna noindex e registra decisões pendentes em `decisoes_do_dono`",
   "sem placeholder: TODO/FIXME/mock/'em breve'/lorem/botão inerte/rota que devolve dado falso em código entregue = erro de build (o driver varre e reprova)",
   "quem constrói não aprova: adversário em contexto próprio, sem ver o raciocínio do construtor, com instrução de derrubar; padrão = 'achei problema'",
   "toda funcionalidade visível tem teste e2e playwright (chromium do playwright; google-chrome headless quebra nesta máquina) com captura salva em tests/e2e/capturas/",
   "commit por turno em português, sem emoji; ledger a cada turno; CHANGELOG.md e MANUAL.md crescem com o produto, nunca no fim",
   "número em documento sai de JSON gerado por script; paridade com Esri só do que foi TESTADO (Pro/AGOL reais = teste do parceiro, registrado como pendente)"
 ],
 "papeis": {
   "gerente": "a sessão que roda a skill: lê estado, escolhe item, escreve o plano do turno, lança os papéis, integra, julga o portão, escreve ledger, comita. Não codifica item médio/grande sozinho.",
   "pesquisador": "pesquisa com fonte datada e URL testada por HTTP; entrega handoff com 'o que muda no item'",
   "arquiteto": "ADR em docs/adr/, contratos de API, esquema, decisões de biblioteca; nunca decide por moda, decide por medição ou por doc oficial",
   "esri": "o que o ArcGIS Enterprise/Pro/AGOL faz EXATAMENTE nessa capacidade (doc Esri datada), lista de paridade feito/parcial/fora, expectativa do usuário Esri",
   "cartografo": "simbologia, projeção, rótulo, legenda, escala, UX de mapa; o mapa tem de ser bonito e correto",
   "redes": "rede de utilidades: topologia, traçado, regras de conectividade, BDGD/CIM/OpenDSS, hierarquia; paridade com Utility Network",
   "raster": "COG/STAC/tiles/sensores/índices; conectores de satélite; proveniência de imagem",
   "dados": "PostGIS/pgRouting/pgstac: esquema, RLS, índices, desempenho medido, migrações",
   "backend": "FastAPI/Python/serviços; testes pytest; OpenAPI",
   "frontend": "MapLibre + app própria; e2e playwright; 0 erro de console; responsivo",
   "testador": "escreve e roda testes independentes do codificador; mede números; reprova sem dó",
   "adversario": "contexto próprio; tenta derrubar o item contra o portão; escreve refutacao.json com veredito e evidência",
   "cronista": "MANUAL.md, CHANGELOG.md, ARQUITETURA.md, página interna do laço"
 },
 "protocolo_de_comunicacao": "Tudo por arquivo em laco/handoffs/T<turno>/<ordem>_<papel>.md, nunca por contexto compartilhado. Modelo: Objetivo · O que fiz · Evidência (comando + saída) · Riscos · Pendências · Para o próximo papel. O gerente lê os handoffs e decide; um papel nunca aprova o próprio trabalho.",
 "backlog": BL,
 "ledger": [],
 "decisoes_do_dono": [
   {"id": "D18", "data": hoje, "pergunta": "nome público do produto (codinome interno: plat)", "estado": "aberta"},
   {"id": "D19", "data": hoje, "pergunta": "URL interna: subdomínio (plat.iagrointel.com, como cbre/fgrsig) × caminho não-adivinhável em iagrointel.com", "estado": "aberta — o laço segue com caminho se não houver resposta"},
   {"id": "D20", "data": hoje, "pergunta": "credencial AGOL/Portal de teste do parceiro para L2-08 (migração) e teste real Pro/AGOL contra nossos serviços", "estado": "aberta"},
   {"id": "D21", "data": hoje, "pergunta": "disco: os dois servidores estão a 98 %. O laço trabalha com ≤ 3 GB; qualquer dado de rede/imagem além disso exige decisão (apagar cópias declaradas em acervo.objeto = 242 GB, ou volume novo)", "estado": "aberta"}
 ],
 "placar": {"entregues": 0, "parciais": 0, "refutados": 0, "total": len(BL), "turnos": 0},
 "notas": [f"{hoje}: laço criado a pedido do dono ('no token limit, no time limit, production, no placeholder, drag-and-drop everything, utility networks'). Ativos reutilizados: fgr/sig (tenant/RLS/FeatureServer), plataforma/pipeline (COG/STAC/TiTiler/Garage), cbre motor AMC (25 fatores), tracado-lt motor (322 camadas), geoapp (conectores globais keyless), BDGD 2024 (101 distribuidoras), acervo.* (376 fontes)."]
}
(B / "estado.json").write_text(json.dumps(estado, ensure_ascii=False, indent=1))
print("itens:", len(BL), "| por linha:", {l: sum(1 for x in BL if x["linha"]==l) for l in dict.fromkeys(x["linha"] for x in BL)})
ids = {x["id"] for x in BL}
bad = [(x["id"], d) for x in BL for d in x["dependencias"] if d not in ids]
print("dependências inválidas:", bad)
