-- 20260906T1901_raster_item: tabela-espelho `plat.raster_item` (item L1-01-a; ADR 0001 seção 3.2 padrão RLS).
-- O pgstac guarda o STAC (coleção/item), mas não sabe o que é "inquilino"; quem autoriza é esta tabela: toda
-- leitura/escrita de imagem passa pela API, que confere aqui (RLS) e no PREFIXO da coleção (`<tenant_id>-slug`,
-- conferido em Python porque `plat.raster_item.tenant_id` já é a fonte da verdade — o CHECK abaixo garante que
-- as duas nunca divirjam: uma linha só existe se a coleção começar pelo tenant_id dela).
CREATE TABLE IF NOT EXISTS plat.raster_item (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_id      int NOT NULL REFERENCES plat.tenant(id),
  colecao        text NOT NULL CHECK (colecao ~ ('^' || tenant_id::text || '-[a-z0-9][a-z0-9-]{0,58}$')),
  item_id        text NOT NULL CHECK (length(item_id) BETWEEN 1 AND 256),
  sha256         text CHECK (sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'),
  perfil         text,
  bytes          bigint CHECK (bytes IS NULL OR bytes >= 0),
  estado         text NOT NULL DEFAULT 'ativo' CHECK (estado IN ('ativo', 'processando', 'erro', 'excluido')),
  criado_em      timestamptz NOT NULL DEFAULT now(),
  atualizado_em  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, colecao, item_id)
);
CREATE INDEX IF NOT EXISTS ix_raster_item_tenant ON plat.raster_item (tenant_id);
CREATE INDEX IF NOT EXISTS ix_raster_item_colecao ON plat.raster_item (tenant_id, colecao);

CREATE OR REPLACE FUNCTION plat.tg_raster_item_atualizado_em() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.atualizado_em := now();
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS raster_item_atualizado_em ON plat.raster_item;
CREATE TRIGGER raster_item_atualizado_em BEFORE UPDATE ON plat.raster_item
  FOR EACH ROW EXECUTE FUNCTION plat.tg_raster_item_atualizado_em();

ALTER TABLE plat.raster_item ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS p_raster_item ON plat.raster_item;
CREATE POLICY p_raster_item ON plat.raster_item FOR ALL TO plat_app
  USING (tenant_id = plat.tenant_atual()) WITH CHECK (tenant_id = plat.tenant_atual());

-- a 001 já dá SELECT/INSERT/UPDATE/DELETE a plat_app em toda tabela nova do schema (ALTER DEFAULT PRIVILEGES);
-- nada aqui precisa de EXECUTE (a tabela não ganhou função própria além do trigger, que roda como dono).
REVOKE ALL ON FUNCTION plat.tg_raster_item_atualizado_em() FROM PUBLIC;
